### ISSUE TITLE
Installing DataSHIELD R packages

### ISSUE THREAD

**Issue by StuartWheater** [obiba/docker-opal#11]
Hello, I attempted to install a DataSHIELD package for GitHub using the Opal Web Portal,
using the page "Administration / DataSHIELD", but no package is added to the list.

The following messages are added to the log.

Stuart
```
> opal_1     | 2019-08-02 15:03:03,880 [qtp1566390876-256] INFO  org.obiba.opal.web.datashield.RPackageResource - installed.packages(fields=c('Title','Description','Author','Maintainer','Date/Publication','AggregateMethods','AssignMethods','Options'))
> opal_1     | 2019-08-02 15:03:03,919 [qtp1566390876-168] INFO  org.obiba.opal.web.datashield.RPackageResource - if (!require('devtools', character.only=TRUE)) { install.packages('devtools', repos=c('https://cloud.r-project.org','https://cran.obiba.org'), dependencies=TRUE) }
```

**Comment by ymarcon** [comment]
You should check the R server output (Rserve.log file) instead. I am pretty sure this is not a docker/opal issue.

**Comment by StuartWheater** [comment]
I was unable to find the Rserve.log file. Is it within the Rserve docker container?

The last message related to Rserve in the docker-compose console output was:
`rserver_1  |  :: Spring Boot ::        (v1.2.2.RELEASE)`

Stuart
