### ISSUE TITLE
Login with KeyCloak forwards to localhost and not to our KeyCloak endpoint on a different server

### ISSUE THREAD

**Issue by IvoLeist** [obiba/docker-opal#14]
Hello Opal Team,

its me again.

since Potgres is now working we want to investigate further if we want
to use Opal for the web application I am building right now.

An additional requirement for us is to have a Keycloak based login.

I followed the tutorial on http://opaldoc.obiba.org/en/latest/web-user-guide/administration/identity-providers.html
and double checked that the URI is in the correct format (https://auth.example.org/.well-known/openid-configuration)

But when I click on Login with keycloak on the login page I always get forwarded to localhost:8080 (on my machine)
and not to the KeyCloak Endpoint on our server.

Do you have any idea what could I have configured wrong?

Best regards,
Ivo

**Comment by kazoompa** [comment]
Hi Ivo,
Can you check your Public URL setting in Opal `Administration /General Configuration`, you may want to change the same URL you have used in KeyCloak. You may have to restart the server as the result.
Best,

**Comment by IvoLeist** [comment]
Hi @kazoompa,

so should I set https://localhost:8843/ as public url? or the url of our KeyCloak endpoint?
What do you mean by restart the server just `docker-compose down` and the `docker-compose up` again?

**Comment by kazoompa** [comment]
You have to put the URL used in Keycloak. 

As for the restart, I think you may not need to restart but in case the URL change did not work. Remember that `docker-compose down` destroys the container. What you want to do is `docker-compose stop <service-name>` and `docker-compose start service-name`. The service name is the one used in the docker-compose.

**Comment by IvoLeist** [comment]
Could you give me an example for an URL to be used in Keycloak? 

I tried:
https://localhost:8843/auth/realms/testrealm/opal
https://opal:8843/auth/realms/testrealm/opal

**Comment by kazoompa** [comment]
If your KeyCloak and Opal containers are on the same server then localhost is the one to use. Basically, the URL that gives access to opal via browser.

**Comment by IvoLeist** [comment]
No the KeyCloak container is on a different server. So I need the IP of the KeyCloak Docker Container?
Or the IP of the Opal Docker Container?

**Comment by ymarcon** [comment]
A public URL is meant to be visible from the outside, more specifically from the keycloak server. So localhost is not appropriate. In production I would expect something like https://opal.example.org.

**Comment by IvoLeist** [comment]
Hello @ymarcon 
thank you for getting involved as well. 

I am afraid there might be a misunderstanding I should have made more clear that we are not yet testing on production but on my local machine. So docker-opal runs on my machine and our KeyCloak docker runs on a different server.

Just to understand the application flow better:
Opal first tries to connect to Keycloak using the Discovery URI if that fails the fallback is the Public URL set in Opal Administration / General Configuration, right?

If that is the case I might have found in the opal:snapshot logs why it is failing:

> [qtp1842844180-305] ERROR org.obiba.oidc.web.filter.OIDCLoginFilter - OIDC login request to 'keycloak' failed.
> org.obiba.oidc.OIDCException: Cannot get OIDC provider metadata for keycloak

> Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: **unable to find valid certification path** to requested target

Thus, we would need to store our authorization certificate in Opal, right? How do you do this?
In the docs (http://opaldoc.obiba.org/en/latest/admin/configuration.html) I only found how to deactivate the certificate check
by setting `org.obiba.opal.security.ssl.allowInvalidCertificates` to true. 

However, since it sounds way more easy to just use a local KeyCloak Container 
> If your KeyCloak and Opal containers are on the same server then localhost is the one to use. Basically, the URL that gives access to opal via browser.

I am going to try that first before spending more time on the issues above.
I'll let you know how that goes.

**Comment by IvoLeist** [comment]
Update:
I might need some help with setting up KeyCloak correctly.
Now when I click on Login with KeyCloak I get correctly forwarded to my KeyCloak Docker but I end up
on the admin level (http://localhost:8080/auth/). Meaning I can only log into the Admin Console.

There is this Base Url setting in Configure - Clients in KeyCloak
at the moment it is empty is this correct or should it be something like:
https://localhost:8843/auth/realms/testrealm/opal ?

If you want to see how I configured Opal / KeyCloak:
https://github.com/ivoLeist/docker-opal

**Comment by ymarcon** [comment]
See this example of KC provider setting in Opal:

```
{
  "name": "kc-test",
  "clientId": "opal",
  "secret": "1aa43945-7166-4292-8f46-c4b836054676",
  "discoveryURI": "https://keycloak.example.org/auth/realms/obiba/.well-known/openid-configuration",
  "scope": "openid profile roles",
  "useNonce": true,
  "customParams": {
    "groups": "datashield",
    "label": "Keycloak Test",
    "providerUrl": "https://keycloak.example.org/auth/realms/obiba/account",
    "enabled": "true"
  },
  "connectTimeout": 500,
  "readTimeout": 500,
  "preferredJwsAlgorithm": null,
  "maxClockSkew": 30
}
```

In KC, you will declare in your realm a client for your Opal server, with "Client Id and Secret" credentials, and a "Valid redirect URIs": will be `http://localhost:8080/auth/callback/*` if you have NOT set a public URL in Opal, or `<your-opal-public-url>/auth/callback/*`.
Replace in the example `https://keycloak.example.org` by what is relevant to you. Same thing with the name of the realm declared in KC (`obiba` in this example), and the "client/secret" strings for the credentials of client.

**Comment by IvoLeist** [comment]
Thank your for the example settings:

I have now set it up like you, but unfortunately it is still failing.

opal:snapshot logs:

> ERROR org.obiba.oidc.web.filter.OIDCLoginFilter - OIDC login request to 'keycloak' failed.
> org.obiba.oidc.OIDCException: Cannot get OIDC provider metadata for keycloak

> Caused by: java.io.FileNotFoundException: http://localhost:8080/auth/realms/opal/.well-known/openid-configuration

Looks like it does not find the file.
But if I navigate from the browser to it I see the configuration like expected.

**Comment by ymarcon** [comment]
you have set the opal url `http://localhost:8080` in place of the keycloak's one. Please follow the instructions carefully.

**Comment by kazoompa** [comment]
I can confirm a successful connection between Opal and KC both of which are installed on two different servers setup for SSL connections.

Here are the steps I followed in KC:
- Created a new client 
- Gave it a ID
- Selected `confidential` for `Access Type`
- Set the redirect URL with a '*' at the end, e.g.: `https://opal.some-domain.org/*`
> This MUST be a publicly accessible URL used as Opal's public URL
- Saved the client
- Selected `Credentials` TAB and regenerated the secret key to be used in Opal

In Opal I used the above information to create a provider (Yannick's example above) and enabled it.

Examples of KC URLs needed in Opal:
- `https://keycloak.other-domain.org/auth/realms/obiba/.well-known/openid-configuration`
- `https://keycloak.other-deomain.org/auth/realms/obiba/protocol/openid-connect/auth`

With the steps above I was able to login as KC user to Opal.

**Comment by IvoLeist** [comment]
@ymarcon
So you mean in my [docker-compose.yml](https://github.com/IvoLeist/docker-opal/blob/master/docker-compose.yml) for keycloak I should not set the ports to 8080:8080 (line 48)?

Anyway we kinda made some progress.
-  Replaced in Opal http://localhost:8080/auth/realms/opal/.well-known/openid-configuration with http://keycloak:8080/auth/realms/opal/.well-known/openid-configuration 
- Added `0.0.0.0   keycloak` to /etc/hosts

Now we are able to see the login page for our realm.
However, log in with our test user leads to a Keycloak window showing a text box with "We are sorry... Page not found"

Below is the address:
http://localhost:8080/auth/callback/keycloak?state=v9pmj5XPHX9pTYbNKYXQPnT4JKFuewoVrwxEU1b0E98&session_state=4cdf7c2a-4985-4821-b41d-2a5e51e26b0d&code=201e9cd3-7b6d-4012-9517-bdcda38bebce.4cdf7c2a-4985-4821-b41d-2a5e51e26b0d.223b3d4a-4f6c-4f60-8346-1a2e2db4ab97

@kazoompa
Thank you for sharing the steps needed for the two server setup.
Did I understood it correctly this only works if both server are publicly available?
So I cannot test the KeyCloak authentication if my Opal runs on localhost on my machine (not publicly accessible)
while our KeyCloak Docker runs on a different server (publicly accessible)

Since this seems to be quite a hassle to test it on localhost I try to do it next week directly on our server :crossed_fingers: 

Thank you for your quick support so far!
I'll keep you updated.

Have a nice weekend :v:

**Comment by ymarcon** [comment]
You can test KC connection with opal running on localhost, you just need to configure the same URL in the opal's public URL property (which default to http://localhost:8080 but if you access differently just set it) and in the KC's opal client valid redirect URL.  OpenID Connect workflow is about redirects and callbacks, so ensure both KC and Opal set ups are consistent.

**Comment by IvoLeist** [comment]
Ok the only missing part which I had troubles to understand that I was not accessing Opal using http://localhost:8080
Thus, I had to set in Opal the public URL to https://localhost:8843

For anyone else stumbling above this if you want to have a working example + a step by step explanation: https://github.com/IvoLeist/docker-opal
