### ISSUE TITLE
Problem with image build

### ISSUE THREAD

**Issue by pschutz-accenture** [obiba/docker-opal#24]
When building the image these errors pops up:

<img width="1099" alt="Snímka obrazovky 2023-05-02 o 10 25 58" src="https://user-images.githubusercontent.com/91953780/235617020-cb23e5a9-3c7c-4aa4-95f7-3f3e58ad13e6.png">

Are you using different approach than building image from gosu as I see it's 5 years old?

**Comment by ymarcon** [comment]
Thanks for the report, it is the build layer that is outdated.
By the way, why do you build your own image?

**Comment by pschutz-accenture** [comment]
Actually I wanted to create a new user which has an administrative rights to opal without the access to see actual data. I did the changes directly in the code, however I am unable to build an image.

**Comment by ymarcon** [comment]
Fix by 34c1d78638416039837c49c1cca178da39945378
