### ISSUE TITLE
Vulnerabilities obiba/opal:4.5

### ISSUE THREAD

**Issue by RonanMorgan** [obiba/docker-opal#25]
Hello, 

According to the "docker scout cves" API there are 35 critical vulnerability in the obiba/opal:4.5 image,

Do you know if any patches will be provided soon ?

Regards,

**Comment by ymarcon** [comment]
Could you share this report? that would help with fixing the issue.

**Comment by ymarcon** [comment]
Please use the email address [dev@obiba.org](mailto:dev@obiba.org) to send this security report.

**Comment by cogliostro** [comment]
Mailed a report generated by trivy (https://aquasecurity.github.io/trivy/) for obiba/opal:4.6

**Comment by cogliostro** [comment]
Your email to group devs@obiba.org was rejected due to spam classification. t_t

**Comment by ymarcon** [comment]
Oh you are using trivy, I will run a scan.

**Comment by cogliostro** [comment]
Did you find anything?

**Comment by ymarcon** [comment]
I am currently testing some library upgrades. Some of them cannot be upgraded because of java version compatibility issues. But this is another topic we are working on... For now, we'll do "best effort" with what we have.

**Comment by ymarcon** [comment]
You can check `obiba/opal:4.6` , there are still 5 critical issues left, limited upgrade is due to java 8 constraint.
