### ISSUE TITLE
default opal config has wrong agate url

### ISSUE THREAD

**Issue by tomkuipers1402** [obiba/docker-opal#29]
Hi,
The default config of opal when launching docker can't connect to Agate, because the URL links to the wrong address:
`org.obiba.realm.url=https://agate:8081`
Currently, HTTPS is linked to the HTTP port. Can this be changed to:
`org.obiba.realm.url=http://agate:8081`
Now after every startup this has to be fixed manually, but would be nice if it's fixed in the image.
Thanks!

**Comment by ymarcon** [comment]
I don't think there is a default config. Which docker env variable do you set?

**Comment by tomkuipers1402** [comment]
If you start the Opal docker container, a config file is generated in /srv/conf called 'opal-config.properties'. In that config, there is this URL to Agate.

**Comment by tomkuipers1402** [comment]
Environment in docker compose contains this for Agate:
````
- AGATE_HOST=agate
- AGATE_PORT=8081
```

**Comment by ymarcon** [comment]
AGATE_HOST and AGATE_PORT are deprecated, use AGATE_URL instead:
https://opaldoc.obiba.org/en/latest/admin/installation.html#docker-image-installation

**Comment by tomkuipers1402** [comment]
Aha, that's good to know & I'll test it out later, but I assume this will fix it.
