### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by mercrat233** [obiba/docker-opal#32]
Hello,

Running docker compose on this repo leads to authentication errors on my system.
My docker-compose file looks like this:

version: '3'
services:
        opal:
                image: obiba/opal:snapshot
                #build: .
                ports:
                        - "8870:8080"
                depends_on:
                        - mongo
                        - mysqldata
                        - mariadbdata
                        - postgresdata
                        - rock1
                        - rock2
                environment:
                        - OPAL_ADMINISTRATOR_PASSWORD=password
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - MONGO_USER=root
                        - MONGO_PASSWORD=example
                        - MYSQLDATA_DATABASE=opal
                        - MYSQLDATA_HOST=mysqldata
                        - MYSQLDATA_USER=opal
                        - MYSQLDATA_PASSWORD=password
                        - MARIADBDATA_DATABASE=opal
                        - MARIADBDATA_HOST=mariadbdata
                        - MARIADBDATA_USER=opal
                        - MARIADBDATA_PASSWORD=password
                        - POSTGRESDATA_DATABASE=opal
                        - POSTGRESDATA_HOST=postgresdata
                        - POSTGRESDATA_USER=opal
                        - POSTGRESDATA_PASSWORD=password
                        - ROCK_HOSTS=rock1:8085,rock2:8085
                volumes:
                        - ./target/opal:/srv
        mongo:
                image: mongo
                environment:
                        - MONGO_INITDB_ROOT_USERNAME=root
                        - MONGO_INITDB_ROOT_PASSWORD=example
        mysqldata:
                image: mysql:5
                environment:
                        - MYSQL_DATABASE=opal
                        - MYSQL_ROOT_PASSWORD=password
                        - MYSQL_USER=opal
                        - MYSQL_PASSWORD=password
        mariadbdata:
                image: mariadb
                environment:
                        - MYSQL_DATABASE=opal
                        - MYSQL_ROOT_PASSWORD=password
                        - MYSQL_USER=opal
                        - MYSQL_PASSWORD=password
        postgresdata:
                image: postgres
                environment:
                        - POSTGRES_DB=opal
                        - POSTGRES_USER=opal
                        - POSTGRES_PASSWORD=password
        rock1:
                image: datashield/rock-base:latest
                environment:
                        - ROCK_ID=default-1
                        - ROCK_CLUSTER=default
        rock2:
                image: datashield/rock-base:latest
                environment:
                        - ROCK_ID=default-2
                        - ROCK_CLUSTER=default

Now when I connect to localhost:8870 I get an authentication error. The Logger gives the two messages that might be related:

WARN  org.jboss.resteasy.resteasy_jaxrs.i18n - RESTEASY002142: Multiple resource methods match request "GET /auth/session/_current/username". Selecting one. Matching methods: [public org.obiba.opal.web.model.Opal$Subject org.obiba.opal.web.security.AuthenticationResource.getSubject(java.lang.String), public org.obiba.opal.web.model.Opal$Subject org.obiba.opal.web.security.AuthenticationResource.getCurrentSubject()] (before I log in)
WARN  org.obiba.shiro.web.filter.AbstractAuthenticationExecutor - Login failed for user 'opal' [1]
INFO  org.obiba.opal.web.security.AuthenticationResource - Authentication failure of user 'opal' at ip: '10.89.1.5': No account information found for authentication token [org.apache.shiro.authc.UsernamePasswordToken - opal, rememberMe=false] by this Authenticator instance.  Please check that it is configured correctly.

In issue #17 the fix had been to use https://localhost, which changes the error. Now, the browser returns one:

Firefox: SSL_ERROR_RX_RECORD_TOO_LONG
Edge: ERR_SSL_PROTOCOL_ERROR ("localhost has send an invalid response")

I use no proxies and checked a couple of versions back
Currently, I am at commit 4ae4aa04e2e0de490f220cc65cdffc7b27d8a5b8..

Thank you for your support.

**Comment by kazoompa** [comment]
Hi,

FYI: I just used your docker-compose and did not have any problem
connecting to http://localhost:8870/.

I ran docker compose up -d on a Ubuntu 22.04, with Docker version 24.0.7,
build afdd53b.

Best,

**Comment by mercrat233** [comment]
And you used the credentials opal:password, right?

**Comment by kazoompa** [comment]
Yes, `administrator`, `password`.

**Comment by mercrat233** [comment]
Thank you for you help! The username was simply wrong.
