### ISSUE TITLE
Set an explicit UID and GID for the `opal` user

### ISSUE THREAD

**Issue by chgl** [obiba/docker-opal#34]
Currently, the `adduser` command tends to create a user with an arbitrary `UID`, depending on the base image (https://github.com/obiba/docker-opal/blob/main/Dockerfile#L66). This makes it difficult to run opal in Kubernetes where explicitly setting the user id and group ip as part of the container's security context is necessary. I noticed this being a problem as both  the `docker.io/obiba/opal:5.0.2` and the `docker.io/datashield/rock-base:6.3.1` tend to change the current UID between updates, causing updates to fail.

It would be great if the `opal` user's user and group id could be set to a fixed value and a `USER` directive be added to the Dockerfile. I'd be happy to create a PR if this seems reasonable!

**Comment by ymarcon** [comment]
PRs are more than welcomed!

FYI I recently tried to replace `gosu` by the `USER` directive but had some issues with access rights on the mounted volume.

**Comment by chgl** [comment]
That's defintely an annoying issue with filesystem permissions - especially if you're mounting a folder on the host filesystem vs just creating a named docker volume. I think it should work if you change the permissions on the host to the same UID/GID as the `USER` directive uses inside the container first, but it would break existing installations.
