### ISSUE TITLE
No such image: sha256:259000*

### ISSUE THREAD

**Issue by bwkchee** [obiba/docker-opal#5]
Previously had this running but blew away the docker images and the repo.  I did a fresh clone of master.  

Docker compose/Docker versions:
docker-compose version 1.5.2, build unknown
docker-py version: 1.8.0
CPython version: 2.7.12+
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
Docker version 17.04.0-ce, build 4845c56

$ docker-compose up
Recreating 1dde45250b_1dde45250b_1dde45250b_dockeropal_rserver_1
Pulling rserver (obiba/opal-rserver:snapshot)...
snapshot: Pulling from obiba/opal-rserver
6d827a3ef358: Pull complete
2726297beaf1: Pull complete
7d27bd3d7fec: Pull complete
e61641c845ed: Pull complete
cce4cca5b76b: Pull complete
6826227500b0: Pull complete
c03b117ffd91: Pull complete
821a1547b435: Pull complete
a75f15aa4d72: Pull complete
f472ce3a0959: Pull complete
1a62425f2621: Pull complete
81bd8d24de35: Pull complete
5b380d01656e: Pull complete
5e565bf3eb24: Pull complete
92a9ff67fe9e: Pull complete
74c74cda86e0: Pull complete
2498b10ba1f9: Pull complete
Digest: sha256:c914e2e5304bf4e67d4148eceb297edcd2e520ed4e384c793be534b0f3e7be71
Status: Downloaded newer image for obiba/opal-rserver:snapshot
ERROR: no such image: sha256:2f9000a3e9f3f837aeb56c1bf880a859d85effbb4df8fd1aad2d18968777ccd3: No such image: sha256:2f9000a3e9f3f837aeb56c1bf880a859d85effbb4df8fd1aad2d18968777ccd3

**Comment by ymarcon** [comment]
Could you try again? because the snapshots of our dockers are rebuilt every night  (2AM EST for opal-rserver) and the corresponding [Docker Hub repo](https://hub.docker.com/r/obiba/opal-rserver/) was maybe in a undefined state.
